local EmoteUi = {
	Crazy = {
		Icon = "",
		Description = "Crazy Whattttttttttt",
		Emote = "rbxassetid://115296259272537",
		Name = "Crazy",
		Price = 200,
	},
	Chill = {
		Icon = "",
		Description = "Chill Guy :)",
		Emote = "rbxassetid://115296259272537",
		Name = "Chill",
		Price = 400,
	},
	Shuffle = {
		Icon = "",
		Description = "Show your moves",
		Emote = "rbxassetid://115296259272537",
		Name = "Shuffle",
		Price = 1000,
	},
}

return EmoteUi
