local NextbotUiInfo = {
	Royal = {
		Icon = "rbxassetid://11375297133",
		Rarity = "Common",
		Description = "HEheha.This guys loves to be annyoing",
		HP = 200,
		Walkspeed = 64,

		Ability = { Ability1 = "Rocket", Ability2 = "nothing", Ability3 = "nothing" },
		AbilityIcons = { "Rocket", "nothing", "nothing" },
		CoinPrice = 200,
	},
	Pork = {
		Icon = "120845391993556",
		Rarity = "Rare",
		Description = "He wants to call everyone",
		HP = 200,
		Walkspeed = 128,

		Ability = { Ability1 = "Rocket", Ability2 = "nothing", Ability3 = "nothing" },
		AbilityIcons = { "Rocket", "nothing", "nothing" },
		CoinPrice = 400,
	},
}

return NextbotUiInfo
