local NextbotUiInfo = {
	--"rbxassetid://124076564998984",
	Royal = {
		Icon = "11375297133",
		Rarity = "Common",
		Description = "HEheha.This guys loves to be annyoing",
		HP = 200,
		Walkspeed = 64,

		Ability = { Ability1 = "Laugh", Ability2 = "Rocket", Ability3 = "nothing" },
		AbilityIcons = { "rbxassetid://93547759136257", "rbxassetid://122710118927247", false },
		CoinPrice = 200,
	},
	Pork = {
		Icon = "120845391993556",
		Rarity = "Rare",
		Description = "He wants to call everyone",
		HP = 200,
		Walkspeed = 128,

		Ability = { Ability1 = "PorkCall", Ability2 = "nothing", Ability3 = "nothing" },
		AbilityIcons = { "rbxassetid://139100209264903", "rbxassetid://80014044533877", false },
		CoinPrice = 600,
	},
	Sanic = {
		Icon = "7425201407",
		Rarity = "Rare",
		Description = "Your to slow ...",
		HP = 200,
		Walkspeed = 128,

		Ability = { Ability1 = "Speedy", Ability2 = "Thunder", Ability3 = "nothing" },
		AbilityIcons = { "rbxassetid://118104684413622", "rbxassetid://124076564998984", false },
		CoinPrice = 400,
	},
}

return NextbotUiInfo
