local player = game.Players.LocalPlayer
local Character = player.Character
local HumanoidRootPart = Character:FindFirstChild("HumanoidRootPart")

local Alignor = Instance.new("AlignOrientation")
--Alignor.Name = "normal"
---Alignor.Parent = HumanoidRootPart
--Alignor.Mode = Enum.OrientationAlignmentMode.OneAttachment
--Alignor.PrimaryAxisOnly = true
--.PrimaryAxis = Vector3.new(0,1,0)

--Alignor.MaxTorque = math.huge
--Alignor.Responsiveness = 50
--Alignor.RigidityEnabled =true
--Alignor.AlignType = Enum.AlignType.PrimaryAxisParallel
--Alignor.Attachment0 = HumanoidRootPart:FindFirstChild("RootAttachment") or HumanoidRootPart:WaitForChild("RootAttachment")
--HumanoidRootPart:FindFirstChild("RootAttachment").Axis = Vector3.new(0,1,0)
--HumanoidRootPart:FindFirstChild("RootAttachment").SecondaryAxis = Vector3.new(0,0,1)





