local createNextBot = {}
--Name ,TextureID,              Walkspeed  idk  SoundId
createNextBot.Royal =
	{ "Royal", "rbxassetid://11375297133", 64, true, "rbxassetid://95039478522269", "FieldOfView", "Rocket", nil }
createNextBot.Pork =
	{ "Pork", "rbxassetid://120845391993556", 80, true, "rbxassetid://95039478522269", "PorkCall", "ShapeShift", nil }
createNextBot.Sanic = { "Sanic", "rbxassetid://7425201407", 100, true, "rbxassetid://95039478522269", "SpeedBoost" }

return createNextBot
