local createNextBot = {}
--Name ,          TextureID,              Walkspeed  idk  SoundId
createNextBot.Royal =
	{ "Royal", "rbxassetid://11375297133", 64, true, "rbxassetid://8417230527", "Laugh", "Rocket", nil }
createNextBot.Pork =
	{ "Pork", "rbxassetid://120845391993556", 67, true, "rbxassetid://99933358254659", "PorkCall", "ShapeShift", nil }
createNextBot.Sanic =
	{ "Sanic", "rbxassetid://7425201407", 75, true, "rbxassetid://95039478522269", "SpeedBoost", "Thunder", nil }

return createNextBot
